@startuml

component "Terminal Application" as App
component "Generic Card API\n(this specification)" as GC #LightYellow
component "Terminal Reader API\n[CNA-TR-API]" as TR

App --> GC : uses
App --> TR : uses
GC  ..> TR : depends on
@enduml
