@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Generic Card API - 2.0.+ (2026-06-12)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or exception
end legend

package "terminal.genericcard" as root {
    +class "**final** GenericCardApiProperties" as ApiProperties <<green>> {
        +{static} **final** String VERSION
    }
    +interface "GenericCardApiFactory" as GenericCardApiFactory <<blue>> {
        +GenericCardSelectionExtension createGenericCardSelectionExtension ()

        +CardTransactionManager createCardTransaction (<back:yellow>CardReader</back> cardReader, <back:yellow>SmartCard</back> card)
    }

    +interface "<<<back:yellow>CardSelectionExtension</back>>>\nGenericCardSelectionExtension" as GenericCardSelectionExtension <<blue>> {
        +GenericCardSelectionExtension addSuccessfulStatusWord (int statusWord)
    }

    +interface "<<<back:yellow><color:blue>IsoCardTransactionManager</back>>>\nCardTransactionManager" as CardTransactionManager <<blue>> {
        +<color:blue>CardTransactionManager prepareCommand (byte[] apdu)
        +<color:blue>CardTransactionManager prepareCommand (byte[] apdu, int idCommand)
        +<color:blue>CardTransactionManager prepareCommand (byte[] apdu, int idCommand, long maxDuration)

        +<color:blue>List<byte[]> getLastExecutionResponses ()
        +<color:blue>byte[] getLastExecutionResponse (int idCommand)
    }
}

' Associations

GenericCardApiFactory ..> GenericCardSelectionExtension #C_LINK : create >
GenericCardApiFactory ..> CardTransactionManager #C_LINK : create >

' == LAYOUT ==

' == STYLE ==

@enduml